#!/bin/bash
# mount data HD
#
# /etc/init.d/my_init.sh

# mount data HD
# id needed put this command above to create folder first
# mkdir /media/carlos/hd
#mount /dev/sda6 /media/carlos/hd/
exec google-chrome-stable; 
